name: duedare_multiple
channels:
  - conda-forge
dependencies:
  - python=3.9.16
  - numpy=1.22.4
  - pandas=1.5.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.1
  - shap=0.42.0
  - xgboost=1.7.4
  - statsmodels=0.14.0
  - ipykernel
  - pip
  - pip:
    - seaborn==0.12.2

